//-----------------------------------------------------------------------------
// Entaro ChucK Developer!
// This is a Chugin boilerplate, generated by chuginate!
//-----------------------------------------------------------------------------

#include <glad/glad.h>
#include <GLFW/glfw3.h>

// this should align with the correct versions of these ChucK files
#include "chuck_dl.h"
#include "chuck_def.h"
#include "ulib_cgl.h"
#include "window.h"

// general includes
#include <stdio.h>
#include <limits.h>

#include <iostream>
#include <cmath>

t_CKBOOL chugl_main_loop_hook(void* bindle)
{
    Window window;
    std::cerr << "INSIDE chugl main loop hook!" << std::endl;

    window.DisplayLoop();

    std::cerr << "==exiting chugl window==" << std::endl;
    CGL::DeactivateHook();

    return TRUE;
}

t_CKBOOL chugl_main_loop_quit(void* bindle)
{
    std::cerr << "LEAVING chugl main loop hook" << std::endl;
    // window.Terminate();
    return true;
}

CK_DLL_QUERY(ChuGL)
{
    // hmm, don't change this...
    QUERY->setname(QUERY, "ChuGL");
    CGL::hook = QUERY->create_main_thread_hook(QUERY, chugl_main_loop_hook, chugl_main_loop_quit, NULL);
    init_chugl(QUERY);
    // wasn't that a breeze?
    return TRUE;
}
